[SPARK-18471][CORE] New treeAggregate overload for big large aggregators
criteo-forks/spark pull request #10
Opened 2016-11-18 10:17 UTC by AnthonyTruchet

## What changes were proposed in this pull request?

The zero for the aggregation used to be shipped into a closure which is
higly problematic when this zero is big (100s of MB is typical for ML).
This change introduces a new overload of treeAggregate which only ships a
function able to generate this zero.

## How was this patch tested?

Unit tests fore core module launched locally

2016-11-18 16:27 UTC, tibidoh requested changes
I think this change is very application specific to be present on core API level. 
Though, as we verbally agreed that this change is rolled back if it is not submitted upstream, I'm OK with it

2016-11-18 16:27 UTC, tibidoh commented on core/src/main/scala/org/apache/spark/rdd/RDD.scala
> +  def treeAggregate[U: ClassTag](zeroValue: U)(
OPT: Please keep BFS order of method declarations

2016-11-18 16:27 UTC, tibidoh commented on core/src/main/scala/org/apache/spark/rdd/RDD.scala
> +   * running on big aggregation structure like large dense vectors
I think where should be no mentions of vector manipulations in core APIs

2016-11-18 17:48 UTC, superbobry commented on core/src/main/scala/org/apache/spark/rdd/RDD.scala
> +  def treeAggregateWithZeroGenerator[U: ClassTag](zeroValueGenerator: () => U)(
You could use a lazy parameter here instead of an explicit closure, see e.g. [this](https://tpolecat.github.io/2014/06/26/call-by-name.html) blog post.

2016-11-21 12:52 UTC, AnthonyTruchet commented on core/src/main/scala/org/apache/spark/rdd/RDD.scala
> +  def treeAggregateWithZeroGenerator[U: ClassTag](zeroValueGenerator: () => U)(
Great suggestion ! I'm not sure however how `lazy val A` a/o `=> A` behave when serialized to an executor... Any idea ?

2016-11-21 12:52 UTC, AnthonyTruchet commented on core/src/main/scala/org/apache/spark/rdd/RDD.scala
> +  def treeAggregate[U: ClassTag](zeroValue: U)(
BFS ? What do you mean ?

2016-11-21 12:57 UTC, tibidoh commented on core/src/main/scala/org/apache/spark/rdd/RDD.scala
> +  def treeAggregate[U: ClassTag](zeroValue: U)(
Breadth first (search) order

2016-11-21 12:58 UTC, tibidoh commented on core/src/main/scala/org/apache/spark/rdd/RDD.scala
> +  def treeAggregateWithZeroGenerator[U: ClassTag](zeroValueGenerator: () => U)(
According to the blog post, it should be exactly what we want. But yeah, we need to test

2016-11-21 13:06 UTC, AnthonyTruchet commented on core/src/main/scala/org/apache/spark/rdd/RDD.scala
> +  def treeAggregateWithZeroGenerator[U: ClassTag](zeroValueGenerator: () => U)(
Let's discuss/test this live because I reckon that the value will be instantiated when thee serializer is called, which is NOT what we want.

2016-11-28 15:56 UTC, AnthonyTruchet commented
This PR is now to be discussed directly here: https://github.com/apache/spark/pull/16038

2016-11-28 15:56 UTC, closed without merging

2016-11-28 15:57 UTC, AnthonyTruchet commented on core/src/main/scala/org/apache/spark/rdd/RDD.scala
> +  def treeAggregate[U: ClassTag](zeroValue: U)(
done

2016-11-28 15:57 UTC, AnthonyTruchet commented on core/src/main/scala/org/apache/spark/rdd/RDD.scala
> +   * running on big aggregation structure like large dense vectors
done