Backporting [SPARK-16494] Upgrade breeze version to 0.12
criteo-forks/spark pull request #13
Opened 2016-11-18 15:55 UTC by eugene-kharitonov

## What changes were proposed in this pull request?

This pull request follows the pull request https://github.com/apache/spark/pull/14150 and updates the breeze version to 0.12. We are interested in it as it allows us to specify convergence criteria in LBFGS.

## How was this patch tested?

MLLib-specific unit tests pass.

2016-11-23 21:54 UTC, superbobry commented on mllib/src/test/java/org/apache/spark/ml/feature/JavaPCASuite.java
> -      Assert.assertEquals(r.get(1), r.get(0));
I wonder what was wrong with the previous version. This isn't breeze-version specific, is it?

2016-12-01 15:56 UTC, AnthonyTruchet requested changes

2016-12-01 15:56 UTC, AnthonyTruchet commented on dev/deps/spark-deps-hadoop-2.2
> +breeze-macros_2.11-0.12.jar
we cannot switch to scala 2_11 I think (see #scala Slack channel for talk initiated by Sergeï)

2016-12-01 15:56 UTC, AnthonyTruchet commented on dev/deps/spark-deps-hadoop-2.2
> +breeze_2.11-0.12.jar
Idem: scala version

2016-12-01 15:56 UTC, AnthonyTruchet commented on dev/deps/spark-deps-hadoop-2.2
> +shapeless_2.11-2.0.0.jar
Idem

2016-12-01 15:56 UTC, AnthonyTruchet commented on mllib/src/test/java/org/apache/spark/ml/feature/JavaPCASuite.java
> -      Assert.assertEquals(r.get(1), r.get(0));
Probably that the previous version does not take numerical / distribution noie into account ?

2016-12-15 09:43 UTC, AnthonyTruchet commented
Looks like #22 just achieed the purpose of this request. I'm closing it.

2016-12-15 09:43 UTC, closed without merging